application: swyzl
version: 5
runtime: python
api_version: 1

handlers:
- url: /media/(.*)
  static_files: media/\1
  upload: media/(.*)

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

- url: /test.*
  script: gaeunit.py

# This URL is for use with the CSV bulk uploader.
# http://code.google.com/appengine/articles/bulkload.html
- url: /load_puzzles
  script: puzzle_loading.py
  # TODO(ijt): This is supposed to be login: admin, but bulkloader.py
  # fails on that.

- url: /load_pack_descriptions
  script: pack_description_loading.py

# Adds puzzles to their named packs if they aren't already in them.
- url: /orphans
  script: orphan_help.py
  # login: admin
  
- url: /.*
  script: main_view.py
